# Generated by Django 5.1.4 on 2025-01-07 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todoitem_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='parent_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child_items', to='todos.todolist'),
            preserve_default=False,
        ),
    ]
